CREATE TABLE DIM_TEMPO (
    ID_TEMPO         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DATA_REFERENCIA  DATE UNIQUE,
    MES              NUMBER,
    NM_MES            VARCHAR2(20),
    TRIMESTRE         NUMBER,
    ANO              NUMBER
);

INSERT INTO DIM_TEMPO (
    DATA_REFERENCIA,
    MES,
    NM_MES,
    TRIMESTRE,
    ANO
)
SELECT DISTINCT
    DT_INTER,
    EXTRACT(MONTH FROM DT_INTER),
    TO_CHAR(
        DT_INTER,
        'Month',
        'NLS_DATE_LANGUAGE=PORTUGUESE'
    ),
    CEIL(EXTRACT(MONTH FROM DT_INTER) / 3),
    EXTRACT(YEAR FROM DT_INTER)
FROM STG_INTERNACOES
WHERE DT_INTER IS NOT NULL;

COMMIT;
