CREATE TABLE DIM_MUNICIPIO (
    ID_MUNICIPIO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CD_IBGE      VARCHAR2(7) UNIQUE
);

INSERT INTO DIM_MUNICIPIO (CD_IBGE)
SELECT DISTINCT TO_CHAR(MUNIC_RES)
FROM STG_INTERNACOES
WHERE MUNIC_RES IS NOT NULL;

COMMIT;
