CREATE TABLE FT_INTERNACOES (
    NR_AIH             VARCHAR2(20) PRIMARY KEY,
    ID_MUNICIPIO       NUMBER REFERENCES DIM_MUNICIPIO(ID_MUNICIPIO),
    ID_TEMPO           NUMBER REFERENCES DIM_TEMPO(ID_TEMPO),
    QT_INTERNACOES     NUMBER DEFAULT 1,
    TEMPO_PERMANENCIA  NUMBER,
    VALOR_TOTAL        NUMBER(12,2)
);

INSERT INTO FT_INTERNACOES (
    NR_AIH,
    ID_MUNICIPIO,
    ID_TEMPO,
    QT_INTERNACOES,
    TEMPO_PERMANENCIA,
    VALOR_TOTAL
)
SELECT
    TO_CHAR(s.N_AIH),
    m.ID_MUNICIPIO,
    t.ID_TEMPO,
    1,
    s.DIAS_PERM,
    s.VAL_TOT
FROM STG_INTERNACOES s
JOIN DIM_MUNICIPIO m
    ON m.CD_IBGE = TO_CHAR(s.MUNIC_RES)
JOIN DIM_TEMPO t
    ON t.DATA_REFERENCIA = s.DT_INTER;

COMMIT;
