-- Quantidade de registros nas tabelas

SELECT 'STG_INTERNACOES' AS TABELA, COUNT(*) AS REGISTROS
FROM STG_INTERNACOES

UNION ALL

SELECT 'DIM_TEMPO', COUNT(*)
FROM DIM_TEMPO

UNION ALL

SELECT 'DIM_MUNICIPIO', COUNT(*)
FROM DIM_MUNICIPIO

UNION ALL

SELECT 'FT_INTERNACOES', COUNT(*)
FROM FT_INTERNACOES;


-- Top 5 municípios por número de internações

SELECT
    m.CD_IBGE,
    COUNT(*) AS QTD
FROM FT_INTERNACOES f
JOIN DIM_MUNICIPIO m
    ON m.ID_MUNICIPIO = f.ID_MUNICIPIO
GROUP BY m.CD_IBGE
ORDER BY QTD DESC
FETCH FIRST 5 ROWS ONLY;


-- Internações por mês

SELECT
    t.ANO,
    t.MES,
    COUNT(*) AS QTD_INTERNACOES
FROM FT_INTERNACOES f
JOIN DIM_TEMPO t
    ON t.ID_TEMPO = f.ID_TEMPO
GROUP BY
    t.ANO,
    t.MES
ORDER BY
    t.ANO,
    t.MES;


-- Média de permanência

SELECT
    ROUND(AVG(TEMPO_PERMANENCIA), 2) AS MEDIA_PERMANENCIA
FROM FT_INTERNACOES;


-- Valor total das internações

SELECT
    ROUND(SUM(VALOR_TOTAL), 2) AS VALOR_TOTAL
FROM FT_INTERNACOES;
